### ISSUE TITLE
Question about underlying scale

### ISSUE THREAD

**Issue by krantzdj1** [jmgirard/CARMA#5]
Hello Dr. Girard,

I am an I/O psychology doctoral student at the University of Akron interested in using your CARMA software. I have a question I can't see directly answered on your website.  I am trying to tell what the underlying scale is. For example, I am probably going to use a -10 to +10 scale with 11 axis steps. But this is all just visual for the participant (correct?), and does not influence the underlying scale that collects movement.  Is the underlying scale -100 to 100 with 201 data points (collected let's say at 10Hz)? Or is it more fine grained than this?

Thank you for your help on this matter and I really appreciate the work you put in to make this software program!

**Comment by jmgirard** [comment]
Thanks for your question. I explained this a little better in the DARMA paper (https://jmgirard.com/pubs/girard2018a/) than I did in the CARMA paper, so it's worth explaining here again.

Basically, the way both programs work is that they will repeatedly measure the position of the slider or joystick at a frequency equal to the "sampling rate" setting (i.e., 10, 20, or 30 times per second). These measurements are all stored in internal memory but then, upon creating the annotation file, the measurements are aggregated into temporal bins (by averaging them). The duration of these bins is determined by the "bin size" setting (i.e., 0.25, 0.50, 1.00, 2.00, or 4.00 seconds).

Next to the slider is a colored rating scale with numbers listed next to tick marks. The range and spacing/number of these tick marks is determined by the "axis numbers" settings (i.e., minimum value, maximum value, and number of steps). The number of axis steps setting is purely visual (for the user) and does not influence the measurements at all. However, the minimum and maximum values are both visual (for the user) and important: they control the range of the ultimate measurements. For example, if you set the scale to range from -10 to 10, then your ultimate bin averages in the annotation file will be between -10 and 10. If they aren't, then there is a problem.

We can verify these statements by looking at the source code. This is one of the beautiful things about open source software.

## Mouse and Keyboard
If you are using the mouse and keyboard input option, then here is the slider and visual rating scale axis being configured.
https://github.com/jmgirard/CARMA/blob/d1722ea831eab6442cc407efb07976ce754425fb/fig_collect_mouse.m#L129-L134
https://github.com/jmgirard/CARMA/blob/d1722ea831eab6442cc407efb07976ce754425fb/fig_collect_mouse.m#L141-L145
Note that the number of axis steps was only used to configure the tick-marks on the rating scale and not to configure the slider. This is important because at each sample, CARMA is actually measuring the position of the slider by querying the slider object itself. Note that this `Value` property is constrained by the `Min` and `Max` properties we configured earlier:
https://github.com/jmgirard/CARMA/blob/d1722ea831eab6442cc407efb07976ce754425fb/fig_collect_mouse.m#L523-L524
The video timestamp and the slider position at that sample are saved to the `ratings` object and then later this is what is aggregated and exported:
https://github.com/jmgirard/CARMA/blob/d1722ea831eab6442cc407efb07976ce754425fb/fig_collect_mouse.m#L539-L549

## Computer Joystick
Things are similar for the joystick input, except that CARMA is actually measuring the position of the joystick by querying the joystick object and not the slider (there is no slider on this window):
https://github.com/jmgirard/CARMA/blob/d1722ea831eab6442cc407efb07976ce754425fb/fig_collect_vrjoy.m#L159
https://github.com/jmgirard/CARMA/blob/d1722ea831eab6442cc407efb07976ce754425fb/fig_collect_vrjoy.m#L532
As described in the `vrjoystick()` function documentation (https://www.mathworks.com/help/sl3d/vrjoystick.html), the "Axis status is returned in the range of -1 to 1." So we need to rescale it to conform to the user's configured minimum and maximum values (we also need to reverse its sign so that pulling towards you results in lower numbers rather than higher numbers):
https://github.com/jmgirard/CARMA/blob/d1722ea831eab6442cc407efb07976ce754425fb/fig_collect_vrjoy.m#L548-L554

**Comment by krantzdj1** [comment]
As an added question - I hope this makes sense - is the timing accuracy dependent on the computer clock? I ask this because I've used a similar, makeshift program from continuous ratings in E-Prime. My understanding of E-prime is that it is particularly robust to potential issues with the computer clock - which is important when trying to get at very minor changes related to reaction time (or for me, potentially syncing this with physio measures.

**Comment by jmgirard** [comment]
> 
> 
> As an added question - I hope this makes sense - is the timing accuracy dependent on the computer clock? I ask this because I've used a similar, makeshift program from continuous ratings in E-Prime. My understanding of E-prime is that it is particularly robust to potential issues with the computer clock - which is important when trying to get at very minor changes related to reaction time (or for me, potentially syncing this with physio measures.

In my experiments, one of which is described in the DARMA paper I referenced above, the delay between subsequent joystick samples was supposed to be 0.050 sec (at 20 Hz), and 95% of them were between 0.049 and 0.057 sec. So there was some inaccuracy on the order of milliseconds. However, since the smallest temporal bin offered by CARMA is 0.25 sec, you can have extreme confidence that the bins correspond to the correct segment of the video.

**Comment by krantzdj1** [comment]
Thanks for the responses, this is very helpful.  So the underlying scale is actually even more detailed - it  goes 3 or 4 decimal points, so that pretty any movement of the slider, no matter how minute or insignificant (I don't mean that in a bad way), will result in a change of the value. Correct?

**Comment by jmgirard** [comment]
> 
> 
> Thanks for the responses, this is very helpful. So the underlying scale is actually even more detailed - it goes 3 or 4 decimal points, so that pretty any movement of the slider, no matter how minute or insignificant (I don't mean that in a bad way), will result in a change of the value. Correct?

Yes, both the slider and joystick values (i.e., `val`) are in double floating-point precision (around 32 decimal points) when saved in internal memory. However, I think that it currently exports them to the annotation file after rounding to four decimal points.

**Comment by krantzdj1** [comment]
Great! Thank you very much.
